spring:
  application:
    name: api.gateway
  cloud:
    gateway:
      routes:
        - id: poc-fse-get
          uri: http://localhost:8700
          predicates:
            - Path=/getSkillDetails/**
server:
  port: ${port:8500}



